import Image from 'next/image'
import MatchCard from '@/components/MatchCard'
import { createServerSupabase } from '@/lib/supabase-server'
import { Match } from '@/lib/types'
export const dynamic='force-dynamic'
export default async function Home(){
 let matches:Match[]=[]; let announcement:any=null
 try{const s=await createServerSupabase(); const {data}=await s.from('matches').select('*').order('date',{ascending:true,nullsFirst:false}).limit(3); matches=(data||[]) as Match[]; const {data:a}=await s.from('announcements').select('*').eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();announcement=a}catch{}
 return <div className="space-y-8">{announcement&&<div className="rounded-2xl border border-red-500/30 bg-red-950/50 p-4"><b>{announcement.title}</b><p className="mt-1 text-sm text-red-100">{announcement.body}</p></div>}<section className="card overflow-hidden p-6 md:p-10"><div className="grid items-center gap-8 md:grid-cols-[1fr_320px]"><div><div className="text-sm font-black uppercase tracking-[.3em] text-red-400">Officiel klubside</div><h1 className="mt-3 text-5xl font-black leading-none md:text-7xl">FC<br/>GLOSTRUPLONA</h1><p className="mt-5 max-w-xl text-lg text-neutral-300">Øl, Damer & Sammenspil. Kampe, resultater, truppen og den officielle FCG-trøje samlet ét sted.</p></div><Image src="/fcg-logo.png" alt="FC Glostruplona logo" width={320} height={320} className="mx-auto"/></div></section><section><div className="mb-4 flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[.25em] text-red-400">Kampcenter</div><h2 className="text-3xl font-black">Kommende kampe</h2></div></div><div className="grid gap-4">{matches.length?matches.map(m=><MatchCard key={m.id} m={m}/>):<div className="card p-6 text-neutral-400">Ingen kommende kampe er annonceret endnu.</div>}</div></section><section className="grid gap-4 md:grid-cols-3"><div className="card p-6"><div className="text-sm text-neutral-400">Hjemmebane</div><div className="mt-2 text-2xl font-black">Glostrup Nou</div></div><div className="card p-6"><div className="text-sm text-neutral-400">Liga</div><div className="mt-2 text-2xl font-black">9. divisionen</div></div><div className="card p-6"><div className="text-sm text-neutral-400">Stiftet</div><div className="mt-2 text-2xl font-black">1142</div></div></section></div>
}
